[package]
name = "deltaq"
version = "0.1.0"
edition = "2024"

[dependencies]
clap = { version = "4.5.47", features = ["derive"] }
deltalake = { version = "0.28.1", features = ["datafusion", "s3"] }
indoc = "2.0.6"
rustyline = "17.0.1"
shell-words = "1.1.0"
tokio = "1.47.1"
